### ISSUE TITLE
Release .apk

### ISSUE THREAD

**Issue by nussbaumer** [SebiderSushi/android-media-rw-remounter#4]
Hello, thanks for the great idea!

Could you please release a compiled apk too?

**Comment by SebiderSushi** [comment]
Hello.
If it is helpful, i would want to have build of this application published.

However, i was hoping to decide for a license and a long-term package name first.
Also, i was planning to release the application to F-Droid, as it could be useful for others as well.

If you are very desperate for write access or very eager to test the app, i will just upload a prerelease.

### Any advice regarding licensing and publishing is welcome.
I want to go with a very permissive license. Since i've read about issues with the legal concept of "public domain" and "unlicensing" i was thinking maybe MIT BSD.

Since i don't have a domain, i am not sure which package name to choose in the long-term.

**Comment by SebiderSushi** [comment]
As of 6ff16f504ab4c3d304ba9baff1cda48f8f8fb047 the package name has been dealt with.
Once legal issues about licensing are sorted out as well i'll consider the app ready for F-Droid.

**Comment by SebiderSushi** [comment]
There is currently an open [Request for packaging in F-Droid](https://gitlab.com/fdroid/rfp/-/issues/1536#note_437231437).
The source code of this application will be maintained [over at ~~github~~ GitLab](https://gitlab.com/giwiniswut/android-media-rw-remounter) in the future, so any further interactions, issues and whatnot should be made over there.

This repository may be archived or even deleted anytime.

**Comment by SebiderSushi** [comment]
In case you didn't follow the [GitLab repository](https://gitlab.com/giwiniswut/android-media-rw-remounter) recently, the app is now available via [F-Droid](https://f-droid.org/packages/com.gitlab.giwiniswut.rwremount/). You can still download it from the [repository's release page](https://gitlab.com/giwiniswut/android-media-rw-remounter/-/releases) if you do not use F-Droid.
